### ISSUE TITLE
ImportError: ../raindance/Lib/LeapSDK/lib/LeapPython.so: invalid ELF header

### ISSUE THREAD

**Issue by unixneo** [ThibaultReuille/graphiti#16]
```
[hawk600:/usr/local/dataviz/graphiti# uname -a
Linux hawk600 3.2.0-115-generic #157-Ubuntu SMP Tue Oct 25 16:32:19 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux](url)

```
```
hawk600:/usr/local/dataviz/graphiti# ./graphiti dashboard
[CLOCK] Clock created at (1479272118 s, 405931 us).
[CLOCK] Clock created at (1479272118 s, 405973 us).
[CLOCK] Clock created at (1479272118 s, 405985 us).
--- Welcome in OpenGraphiti (Alpha) ---
[API] create(2, 0x7ffd1e4732e8)
[__INIT__]
Traceback (most recent call last):
  File "./Scripts/start.py", line 5, in <module>
    from Scripts import *
  File "./Scripts/__init__.py", line 14, in <module>
    import leap
  File "./Scripts/leap.py", line 16, in <module>
    import Leap, sys, thread, time
  File "../raindance/Lib/LeapSDK/lib/Leap.py", line 28, in <module>
    LeapPython = swig_import_helper()
  File "../raindance/Lib/LeapSDK/lib/Leap.py", line 24, in swig_import_helper
    _mod = imp.load_module('LeapPython', fp, pathname, description)
ImportError: ../raindance/Lib/LeapSDK/lib/LeapPython.so: invalid ELF header
[RESOURCE]
    Total : 0 resources, 0 bytes.
```

Actually, I am running OG on a remote Linux server  vis ssh -X on my local Mac so I don't need LEAP on the remote server at this point in time.

Any suggestions?

**Comment by unixneo** [comment]
Please close this issue as we are currently developing with Unity 3D.
